# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b7701ba02abefef6be470c5c63e437c431d0a5ecc6de20a5853e3fe11611afa3b268151f639253243e5d4c692a1547915c71631a7e80587364b1984d1d9d152

test:
  secret_key_base: 3c5fbd2fc8345ab7355293e1cd0b72f4ba03a1b61ce28c405bb2558a00ee17dd4ca789176f01db1a310668cede8fc006ab953f4b9b9829d1c00a15fb66658109

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
